### ISSUE TITLE
About error on recent asset files

### ISSUE THREAD

**Issue by garamika** [OpenMLTD/MLTDTools#12]
I tried to convert recent asset files with MillionDance - after the Unity engine version update, and the program spat out "System.NullReferenceException" error.
This seems to be the error caused by the change of Unity engine version of MLTD - which had changed the version to 2018 from 2017.f2 recently. It seems that the UnityEngine component in the program does not support the unity3d file.
Is there any way to figure out the problem?
![adsfdf](https://user-images.githubusercontent.com/50797622/71458801-db655000-27e7-11ea-8894-edfc8a909110.PNG)

**Comment by hozuki** [comment]
Can you confirm that this problem is solved?

**Comment by garamika** [comment]
Sorry for late reply. This has been resolved and I forgot to comment.
I closed the issue.
