### ISSUE TITLE
some exes not opening

### ISSUE THREAD

**Issue by akaneP** [OpenMLTD/MLTDTools#14]
AcbPack, HcaDec, and ManifestExport do not open, and only open like a command prompt. Opening in Compatibility Windows 8 mode and giving Admin do not work. Along with this, MillionDance does not recognize files exported from MLTD Asset Downloader

**Comment by hozuki** [comment]
Those three are [command line programs](https://en.wikipedia.org/wiki/Command-line_interface), which means they are *designed* to function without a graphical interface. You need to run them in CLI. They do not need compability mode or admin priviledges.
If you are not familiar with CLI, you can read some tutorials. For example [this one](https://superuser.com/questions/494538/how-do-i-open-a-program-via-the-command-prompt-in-windows-8).

Starting from ~2 years ago (mid-2018?) downloading MLTD assets requires authentication. So the downloader creates a new file (it uses `WebClient` internally) tries to download, but encounters a 403 error. The file remains empty, zero-length and they are invalid. There are some ways to fix it but they involve things which should not be placed in public repositories. Maybe some day someone will find a better way to bypass that.
Instead you can use the cached files on your phone. Oh and I haven't fixed #12 yet... I was too long gone. 😞

**Comment by hozuki** [comment]
Just a side note. You can find an asset downloader [here](https://github.com/KinoMyu/MLTD-Asset-Downloader). Then integrating this is not at highest priority now.

**Comment by hozuki** [comment]
The latest auto build contains an improved manifest tool. Feel free to try it out.

**Comment by hozuki** [comment]
Can you confirm that this problem is solved?

**Comment by akaneP** [comment]
it worked! thank you!
