### ISSUE TITLE
Supporting new animations (body, camera, facial expressions)

### ISSUE THREAD

**Issue by hozuki** [OpenMLTD/MLTDTools#16]
Commit 3e21599d466ea929d8dabb44926b243096995aee added support for the new body animations (`dan_*_xx.unity3d`, without `.imo`). Please check out the [auto builds](https://ci.appveyor.com/project/hozuki/mltdtools/build/artifacts) and have a try. I'll make a new release after these functions are stable.
I haven't investigated camera data yet.

Related issues: #15 #12 #9
Related users: @garamika @Reona945

**Comment by Reona945** [comment]
Hello! I have not been able to convert an dan_alstar_01.imo.unity3d successfully. Spits out the failed to load dance error out. was this update just for animations with different name inputs? or for unsupported animations? 

![image](https://user-images.githubusercontent.com/58755639/81484115-fdd89280-91f7-11ea-943b-d4733e7c9482.png)

**Comment by hozuki** [comment]
This is for supporting unsupported animations (the ones without `.imo` in their names). Simply concluded, `dan_xxx.unity3d` and `dan_xxx.imo.unity3d` contains the *same animation* in *different formats*. I tested with `dan_rebell_01.unity3d`.
I'll test these files (`alstar`) soon and try to find out what happened.

**Comment by hozuki** [comment]
The cause is that, some assets (`dan` and `apg`) in `alstar` has `.asset` postfix. Such names should be a mistake in the bundling process. (Not funny, BNSI.)
Searching logic is adapted in 2398382b0ac1c3d3288dc52e7260766bef449691. A new auto build should be out soon.

**Comment by hozuki** [comment]
Only a very limited number of songs use `AnimationClip` dance animations (those without `.imo` in their names). Is that because of technical limitations?
Camera animations, on the other hand, all use legacy, compiled-on-the-fly animations (`.imo`).
