### ISSUE TITLE
Supporting alternative appeals

### ISSUE THREAD

**Issue by hozuki** [OpenMLTD/MLTDTools#17]
Some animations have *special appeal* (e.g. [`gf0000`](https://www.project-imas.com/wiki/G%E2%99%A1F), 1 available appeal), and some of these have a second *another appeal* (e.g. [`kururi`](https://www.project-imas.com/wiki/Kururi_Uta), 2 available appeals). These animations are played when the player completes a full combo before the large note.
`dan` files usually contain `apa` and `apg`, but some even have a companion `_ap` file. (#11) `cam` files usually contain `apa` and `apg` but none of them has `_ap` file.

Questions:

1. What do `apa` and `apg` stand for, i.e. which one is which?
2. If those two correspond to the alternative appeals, what role does `_ap` file play?

**Comment by hozuki** [comment]
`kururi` should be an interesting sample:

- it has a companion `_ap` file;
- there are *2* animations in the intro, but only *1* dance animation;
- such signature is not found in other songs with `_ap`.

There is no `apa` or `apg` located in the main dance animation file. Instead, in the `_ap` file there are:

- `01_apa` (and `01_apa.opt` as some kind of control?)
- `01_apg`
- `02_apa` (+`02_apa.opt`)
- `03_apa`
- `04_apg`
- `05_apg`

There are two endings: special appeal (with Chizuru & Shiho), and another appeal (with Kaori & Elena).
Positions: [4] Chizuru | [2] Elena | [1] Akane | [3] Kaori | [5] Shiho
So we can somewhat deduce what `apa` and `apg` are...

**Comment by garamika** [comment]
It seems like "apa" is another appeal and "apg" is special appeal. I tried to rip motions by simply changing the name of the file to "dan" inside the package - using UABE.

**Comment by hozuki** [comment]
Yep and it's time to design file selection and replacing the animations at the right time.

**Comment by hozuki** [comment]
Dance and camera animations should be correctly converted by now.
