### ISSUE TITLE
MillionDance error

### ISSUE THREAD

**Issue by mxze** [OpenMLTD/MLTDTools#19]
Hello, I tried using MillionDance with files from the latest version/manifest of the game, and the latest version of this program (CI auto build). It gave me this error while trying to just export a model (no dance, facial, camera, or lip sync, all other settings on default).
![Screenshot](https://user-images.githubusercontent.com/57579088/82088313-84411880-96bf-11ea-841f-458730fceba9.png)

I can't really tell if it's an error on my side or not but if it's something I'm doing wrong I'd really appreciate being told what. If I need to provide more info I can do that too. Thank you for keeping this program updated even to this day!

**Comment by hozuki** [comment]
Sorry, I forgot to check the consistency of dependency libraries. Pushed fa95308a65ede158b5911e94c03a4771fc843260 and now it's fixed.

**Comment by mxze** [comment]
It works now, thanks so much!!
