### ISSUE TITLE
MillionDance

### ISSUE THREAD

**Issue by FantasyGmm** [OpenMLTD/MLTDTools#2]
I have all Resources,
![image](https://user-images.githubusercontent.com/16450052/43364002-d6d1c2b0-9343-11e8-9b1c-455df0e9a0c7.png)
,but when i run this process, display:System.NullReferenceException

**Comment by hozuki** [comment]
Can you provide some debug information please?

**Comment by fantasy2333** [comment]
![qsn az97 vspo4dz1 94 yd](https://user-images.githubusercontent.com/16450052/43653122-b92c5ba0-9779-11e8-84d4-d4e99a9bbce5.png)
![w90foacnxm nud1d3 jwuvl](https://user-images.githubusercontent.com/16450052/43653123-ba137576-9779-11e8-89e3-cfcf397c5b79.png)
就像这样，要啥文件全都放进去了

**Comment by hozuki** [comment]
It's obvious that the avatar was not found in the model bundle. You must have selected a wrong file.

**Comment by fantasy2333** [comment]
ok,i will try other model

**Comment by fantasy2333** [comment]
thx

**Comment by hozuki** [comment]
BTW the GUI application of MillionDance is made. You can try it out.
