### ISSUE TITLE
problem with "Re@dy"

### ISSUE THREAD

**Issue by Sozuke** [OpenMLTD/MLTDTools#20]
Million dance exports the first dance well but the others don't work.

I checked the files thinking they were "broken", but they are different from the first one, they contain the dan and idl but they don't contain the apa and apg, only the first one has the complete files (dan, apa, apg, idl

**Comment by hozuki** [comment]
Thanks. Fixed in commit d1f85720cd53a130e345b139d3e014a265ef426c. A new CI build is out, have a try.

**Comment by Sozuke** [comment]
Thanks to the update some new dances can now be exported
