### ISSUE TITLE
About lip-sync error on specific song

### ISSUE THREAD

**Issue by garamika** [OpenMLTD/MLTDTools#22]
On exporting the lip-sync of the song "Alive Factor" this error message pops up.
(sorry for the language - I use Korean windows)

![캡처](https://user-images.githubusercontent.com/50797622/83356637-6273b100-a3a2-11ea-83e9-1d618e2d686e.PNG)

"System.ArgumentOutOfRangeException : Not possible
variable name : lipCode
the actual value is 55."

Could you investigate the cause of this error?
Thanks in advance.

**Comment by hozuki** [comment]
I tried to fix it in commit 84d21efc03aef3f61c6ba8b475e28900088a03c4. A new CI build is out.

I watched some reference videos but I'm not sure what those values exactly stand for (see comments [here](https://github.com/OpenMLTD/MLTDTools/blob/84d21efc03aef3f61c6ba8b475e28900088a03c4/src/MillionDance/Core/VmdCreator.FacialExpressions.cs#L393-L397)). It is not as easy to guess as the values before. But the conversion result looks good so far.

**Comment by garamika** [comment]
Thanks for the fix!
It worked and the result is good.
But the same error occured when I try to convert the lipsync of idol 2. Is it the problem of idol position?

**Comment by hozuki** [comment]
Hmm, it's my oversight. I forgot to check the one for idol 2. Committed 8b60d703fbc445acac301e9ef2273785cd7e885d.

So now these codes seem to be "meta-control"s and they don't have direct influence on the lip morphs... Also changed to ignore these (known) codes in the new commit.

**Comment by hozuki** [comment]
Can you confirm that this problem is solved?

**Comment by garamika** [comment]
Sorry for late reply. This has been resolved and I forgot to comment.
I closed the issue.
