### ISSUE TITLE
How to find models?

### ISSUE THREAD

**Issue by animegamer89** [OpenMLTD/MLTDTools#24]
Trying to find the unity3d models from cache00 folder. But all of them now has a bunch of numbers and letters. How would I know if the unity3d models are there?

**Comment by hozuki** [comment]
I haven't investigated how the names are mapped and I don't want to waste time doing that (it may be hard) unless it's absolutely necessary.

For now you can use manifest tools in this repository, or [asset downloader](https://github.com/KinoMyu/MLTD-Asset-Downloader), to directly download the files.

**Comment by animegamer89** [comment]
Okay, got it. Thanks for your help!
