### ISSUE TITLE
some keys of expression

### ISSUE THREAD

**Issue by Sozuke** [OpenMLTD/MLTDTools#28]
I'm not sure which are 16 and 17 yet, I'm still trying, but some of them seem to correspond to how the mv or the dress works

note: for some reason, the default expression is duplicated every time I load or save the file

![Facial Expression Mapping Editor 24_07_2020 02_51_14 p  m](https://user-images.githubusercontent.com/48562770/88429937-303c6980-cdbd-11ea-82ef-7710eda784ad.png)

here: https://mega.nz/file/GGgFlAJS#yIhG2V-1DzwPpEubDK57KdjD9WuQcvRQdYwr6ivG1T8

**Comment by hozuki** [comment]
You can make a pull request to update the json file if you think the values are okay. :D

**Comment by Sozuke** [comment]
update:


I don't know how to make a pull request :P

[facial_expr.zip](https://github.com/OpenMLTD/MLTDTools/files/5043880/facial_expr.zip)

**Comment by hozuki** [comment]
Don't worry. I'll do it then.
