### ISSUE TITLE
A small bug when exporting cameras in vmd.

### ISSUE THREAD

**Issue by Sozuke** [OpenMLTD/MLTDTools#31]
The fov is now constant, but for some reason the cameras come out inverted (this only happens in vmd) I mean, it is the correct position, but look the other way, I found a way to fix it but it made me curious

Also: mmd does not read the camera the same as miku moving since miku moving apparently ignores the model name (model / camera) and loads them, but mmd does not load the cameras, since the model name does not match, it puts the error as if it were a normal motion instead of a camera

How to fix it in mmd:

https://mega.nz/file/OX52USbY#YZ9lWILSSd3KhG5cYlgGuaksPgjAQg_yIr0onG1F34E

I really don't know, I tried to see what the problem is by converting an mmd camera and one generated in million dance to readable text (vmd exploring tools) but despite having the same data both files had a different header

**Comment by hozuki** [comment]
Thank you for the experiments and the guide! Now the camera works directly in MMD.

Apart from the positions and angles (so MMD and MMM are using different coordinate conventions), the "object name" field of motion data has to *start with* `カメラ・照明` ("camera & lighting" in Japanese). Figured out by reading some valid camera motion files.
