### ISSUE TITLE
Not supported when appending bone is enabled

### ISSUE THREAD

**Issue by maplestyle** [OpenMLTD/MLTDTools#7]
![20181025233058](https://user-images.githubusercontent.com/41418628/47512146-2915be00-d8ae-11e8-8612-3639b06d6845.png)
When check "Append Leg IK bones"、"Append eye pose", it'll always show this error

**Comment by hozuki** [comment]
Hmm it's not possible to use MLTD (and convert) motions with bones modified (appending IK, eyes, and semi-standard bones), at least for now. The UI should reflect this. I'll fix the UI guidance so you'll not choose impossible combinations again. It's also time to think about writing a manual...

**Comment by hozuki** [comment]
I think the impossible combinations are excluded by control states (enabled or not) now. Please check the latest auto build.

[Related commits](https://github.com/OpenMLTD/MLTDTools/compare/bab25cf02efe2bddaff6437d06eb38cd9aba1bd7..b9691b70c52570b1ffbbd5de39802b3da7076053)

**Comment by hozuki** [comment]
This bug does not occur in later builds.
